apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-default-fld
  labels:
    app: ubuntu
spec:
  containers:
  - image: ghcr.io/pluhin/busy-box:shatest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu-default
